### ISSUE TITLE
Cannot Run the script

### ISSUE THREAD

**Issue by spinalgr1990** [cyclone-github/TeamViewer_ID_Reset#1]
I Cannot Run the script

can you release an .exe file ?

**Comment by cyclone-github** [comment]
The Windows version is not a script, it is source code which requires compiling.
- "_This tool is written in go, so it will need compiled before running._"
- Compile from source code how-to:
  - https://github.com/cyclone-github/scripts/blob/main/intro_to_go.txt

**Comment by spinalgr1990** [comment]
can you upload here the go script ? Then remove the post after some days
