### ISSUE TITLE
About Reset

### ISSUE THREAD

**Issue by ghost** [cyclone-github/TeamViewer_ID_Reset#2]
Hello,

Can this tool be used to reset for portable versions and version 15?

@cyclone-github

**Comment by delevic** [comment]
Wont work on latest update. They changed something.

**Comment by cyclone-github** [comment]
Tool is no longer working on Windows. https://github.com/cyclone-github/TeamViewer_ID_Reset/commit/bf45dbae1b8b6a5de7fc67f0fdb02be0d7a1fa3b
I am currently not maintaining this repo, but will leave the code up for reference.
